update B_CLASS_FIELD set SHOW_NAME_CH = '新车型实施日期' where uuid='21' and field_name='EXECUTE_DATE_STR';
update B_CLASS_FIELD set SHOW_NAME_CH = '生效日期' where uuid='19' and field_name='PRE_EXECUTE_DATE_STR';
update B_CLASS_FIELD set SHOW_NAME_CH = '强制性' where uuid='45' and field_name='ISMANDATORY';
update B_CLASS_FIELD set SHOW_NAME_CH = '动力类型' where uuid='44402' and field_name='POWER_TYPE';
update B_CLASS_FIELD set SHOW_NAME_CH = '整车/零部件' where uuid='44' and field_name='ISPARTS';
update B_CLASS_FIELD set SHOW_NAME_CH = 'MIIT公告' where uuid='47' and field_name='ISBULLETIN';
update B_CLASS_FIELD set SHOW_NAME_CH = '修订版/新版' where uuid='44403' and field_name='REVISION_EST';
update B_CLASS_FIELD set SHOW_NAME_CH = '地方排放' where uuid='44407' and field_name='IS_LOCAL_EMI';
update B_CLASS_FIELD set SHOW_NAME_CH = '新车型实施日期' where uuid='3321' and field_name='EXECUTE_DATE_STR';
update B_CLASS_FIELD set SHOW_NAME_CH = '生效日期' where uuid='33319' and field_name='PRE_EXECUTE_DATE_STR';
update B_CLASS_FIELD set SHOW_NAME_CH = '强制性' where uuid='3345' and field_name='ISMANDATORY';
update B_CLASS_FIELD set SHOW_NAME_CH = '动力类型' where uuid='133' and field_name='POWER_TYPE';
update B_CLASS_FIELD set SHOW_NAME_CH = '整车/零部件' where uuid='3344' and field_name='ISPARTS';
update B_CLASS_FIELD set SHOW_NAME_CH = 'MIIT公告' where uuid='3347' and field_name='ISBULLETIN';
update B_CLASS_FIELD set SHOW_NAME_CH = '修订版/新版' where uuid='44411' and field_name='REVISION_EST';
update B_CLASS_FIELD set SHOW_NAME_CH = '地方排放' where uuid='136' and field_name='IS_LOCAL_EMI';
commit;